# Generated by Django 5.0.3 on 2024-05-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='uploads/service')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(upload_to='uploads/house'),
        ),
    ]
