# Generated by Django 5.0.3 on 2024-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_remove_service_image_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main_img',
            field=models.ImageField(default=0, upload_to='uploads/service_images'),
            preserve_default=False,
        ),
    ]
